services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  redis:
    image: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    depends_on:
      - redis
  nginx:
    build:
      context: ../../
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf
      - ../../assets:/usr/share/nginx/assets
    depends_on:
      - application
  application:
    build:
      context: ../../
      dockerfile: ./infra/dev/Dockerfile
    env_file:
      - .env
    volumes:
      - ../../:/app
      - cargo-target:/app/target
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  pgadmin:
  redisdata:
  redisinsight:
  application:
  cargo-target:
